POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVlOGNjZmQwMGI4MmI5MGNkYzE5MWYxMyIsImlhdCI6MTU4NjI5MzAyM30.eHIUdHDRJwey5wUwWm5IhUIIV-Pda5V-LOh7TwBAXJw

{
  "title": "blog for deleting",
  "author": "will be deleted",
  "url": "www.fakeurl",
  "likes": 3
}